# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFcZ-C3mclTvax4PeEKEz3Igls5yCjRT
"""

import pandas as pd
f=pd.read_csv("/content/data.csv")
print(f)
r,c=f.shape
print("size of csv file:: ")
print(r,c)
print("Printing Head part")
print(f.head())
print("Printing tail part")
print(f.tail())
print("Printing specific Data")
print(f[2:3])
print(f.iloc[1:3,1:4])
print("Printing the 0 index value")
print(f.loc[0])
print("Printing Columns")
print(f.columns)
print("Print the CGPA")
print(f.CGPA)

import pandas as pd
import numpy as np
f=pd.read_csv("/content/data2.csv")
print(f)
r,c=f.shape
print("size of csv file:: ")
print(r,c)
print("Printing Columns:: ")
print(f.columns)
print("Mid sem Highest mark",f.Mid_sem.max())
print("Mid sem Lowest mark",f.Mid_sem.min())
print("ENd sem Highest mark",f.end_sem.max())
print("End sem Lowest mark",f.end_sem.min())
print(f[:])
a=[f.Test_grade > 9]
print(a)
b=f.Test_grade.max()
print("Maximum Test Grade",b)
print("Mean Value of mid sem",np.mean(f["Mid_sem"]))
print("Median Value of mid sem",np.median(f["Mid_sem"]))
print(np.var(f["Mid_sem"]))
print(np.std(f["Mid_sem"]))
print("CHceking if there any vacant")
print(f.isnull())
print(f["total"].isnull())
print(f["Test_grade"].isnull())
print(f["grade"].isnull())
f2=f.fillna(0)
print(f2[:])
print("Mean Value of Hour Studied",np.mean(f["Hours_studied"]))
print("Mean Value of Test Grade",np.mean(f["Test_grade"]))

import pandas as pd
import numpy as np
f=pd.read_csv("/content/data3.csv")
print(f)
r,c=f.shape
print("size of csv file:: ")
print(r,c)
print("Printing Columns:: ")
print(f.columns)
print("Mid sem Highest mark",f.Mid_sem.max())
print("Mid sem Lowest mark",f.Mid_sem.min())
print("ENd sem Highest mark",f.end_sem.max())
print("End sem Lowest mark",f.end_sem.min())
print(f[:])
a=[f.Test_grade > 9]
print(a)
b=f.Test_grade.max()
print("Maximum Test Grade",b)
print("Mean Value of mid sem",np.mean(f["Mid_sem"]))
print("Median Value of mid sem",np.median(f["Mid_sem"]))
print(np.var(f["Mid_sem"]))
print(np.std(f["Mid_sem"]))
print("CHceking if there any vacant")
print(f.isnull())
print(f["total"].isnull())
print(f["Test_grade"].isnull())
print(f["grade"].isnull())
f2=f.fillna(0)
print(f2[:])