# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3nNkDmD2VPgvzYZV_sfuzK8xqqCb1nn
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv('/content/Salary.csv')
print(df)

plt.xlabel('Age')
plt.ylabel('Salary')
plt.title('Scatter Plot')
plt.scatter(df['Age'],df['Salary'])
plt.show()

df.plot.scatter(x='Age',y='Salary')

# Salary Line Chart
plt.plot(df['Salary'])
plt.title('Line Chart(Salary)')
plt.show()

#plt.plot(df['Age'])
#plt.plot(df['Salary'])
plt.plot(df['Age'],df['Salary'])
plt.title('Line Chart of Age and Salary')
plt.show()

plt.bar(df['Age'],df['Salary'])
plt.title('Bar Chart of Age and Salary')
plt.show()

#Histogram using
column = (df['Purchased'])
plt.hist(column)
plt.title('Histogram')
plt.show()

#histogram using pd
df['Purchased'].hist()

#Box plot
x = df['Age']
y = df['Salary']
columns=(x,y)

df.boxplot('Salary',grid=False)

df.boxplot('Salary',grid=True)