# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bk24KO78GEBcVzTrjfDzItEqucR2F09l
"""

import pandas as pd
import numpy as np
df=pd.read_csv('/content/house-updated.csv')
print(df)

# Showing in Scatter Plot
import matplotlib.pyplot as plt
plt.scatter(df['Area'],df['Price'])
plt.show()

x=df['Area']
y=df['Price']
x_mean=np.mean(x)
y_mean=np.mean(y)
print(x_mean,y_mean)

# Calculating the slope of the reg. line

numerator = ((x-x_mean)*(y-y_mean)).sum()
print(numerator)
denominator = ((x-x_mean)**2).sum()
print(denominator)

# Calculation of the inter

c = y_mean - ((numerator/denominator) * x_mean )
m=numerator/denominator
print(m,c)

y_prod=m*x+c
plt.scatter(x,y)
plt.plot(x,y_prod)
plt.show()

from sklearn.linear_model import LinearRegression
df=pd.read_csv('/content/house-updated.csv')
x=df.iloc[:,:-1]
y=df.iloc[:,1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
model=LinearRegression()
model.fit(x_train,y_train)
print(model.coef_)
print(model.intercept_)
predictions=model.predict(x_test)
plt.scatter(y_test,predictions)
from sklearn import metrics
metrics.mean_squared_error(y_test,predictions)