# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17602yVXZWhmf6lebDPKQxY0rypzvas-w
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris=load_iris()

iris.feature_names

iris.target_names

df=pd.DataFrame(iris.data,columns=iris.feature_names)
df

df['target']=iris.target
df

df[df.target==0]

df0=df[:50]
df1=df[50:100]
df2=df[100:]

from sklearn.model_selection import train_test_split

x=df.iloc[:,[1,2,3,4]].values
y=df.iloc[:,-1]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

len(x_train)

len(x_test)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train,y_train)

knn.score(x_test,y_test)

from sklearn.metrics import confusion_matrix

y_pred=knn.predict(x_test)

cm=confusion_matrix(y_test,y_pred)
cm

import seaborn as sn
plt.figure(figsize=(7,5))
sn.heatmap(cm,annot=True)
plt.xlabel("Predicted")
plt.ylabel("Truth")

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))