# -*- coding: utf-8 -*-
"""lab7_eva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iArJmmFLgR9GyWnLNSBYQ87IyMOCEVNj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/employee_updated.csv')
df

df[df.Purchased==1]

from sklearn.model_selection import train_test_split

x=df.drop(['Purchased','Gender'],axis='columns')
y=df.Purchased

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

len(x_train)

len(x_test)

from sklearn import svm

model=svm.SVC(kernel='linear')

model.fit(x_train,y_train)

model.score(x_test,y_test)

from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
cm

import seaborn as sn
plt.figure(figsize=(7,5))
sn.heatmap(cm,annot=True)
plt.ylabel('Predicted')
plt.xlabel('Truth')

from sklearn.svm import SVC
classifier = SVC(kernel ='rbf', random_state = 0)
# training set in x, y axis
classifier.fit(x_train, y_train)

classifier = SVC(kernel ='sigmoid')
classifier.fit(x_train, y_train) # training set in x, y axis